version: '3.2'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src/public:/var/www/public
    depends_on:
      - api

  db:
    image: mysql:8.0
    env_file:
      - ./.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    volumes:
      # - mysql_db:/var/lib/mysql
      - ./docker/db/mysql_data:/var/lib/mysql
    ports:
      - 4306:3306

# volumes:
  # mysql_db:
