version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

# ---------------- Commands ----------------

commands:
  env_setup:
    steps:
      - run:
          name: ENV Setup
          command: |
            echo $ENV_FILE | base64 -di > .env
            echo $TEST_ENV_FILE | base64 -di > src/.env.testing

  docker_setup:
    steps:
      - run:
          name: Docker Setup
          command: |
            docker-compose -f docker-compose.yml up -d

  laravel_setup:
    steps:
      - run:
          name: Laravel Setup
          command: |
            docker-compose -f docker-compose.yml run api composer install

  test_run:
    steps:
      - run:
          name: Run Test
          command: |
            docker-compose -f docker-compose.yml run api php artisan test

  fixer_run:
    steps:
      - run:
          name: Fixer Test
          command: |
            docker-compose -f docker-compose.yml run api ./vendor/bin/php-cs-fixer fix --diff --dry-run .

  api_image_push:
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          path: .
          dockerfile: ./docker/api/Dockerfile
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "wedding-photo-api_api"
          tag: ${CIRCLE_SHA1}


  nginx_image_push:
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          path: .
          dockerfile: ./docker/nginx/Dockerfile
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "wedding-photo-api_nginx"
          tag: ${CIRCLE_SHA1}

  test_notification:
    steps:
      - slack/status:
          success_message: ':circleci-success: $CIRCLE_BRANCH のテストが完了しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-failed: $CIRCLE_BRANCH のテストが失敗しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'

  test_notification_to_discord:
    steps:
      - run:
          name: Notify to discord
          command: |
            curl -sS -XPOST -H "Content-Type: application/json" \
            -d '{"content": "Build: ['"$CIRCLE_JOB: $CIRCLE_PREVIOUS_BUILD_NUM"']('"$CIRCLE_BUILD_URL"')\n\n Status: ['"$CIRCLE_BRANCH"']('"$CIRCLE_PULL_REQUEST"')のテストが完了しました\n\n User: '"$CIRCLE_USERNAME"'"}' \
            $DISCORD_WEB_HOOK_URL >/dev/null

  ecr_notification_to_discord:
    steps:
      - run:
          name: Notify to discord
          command: |
            curl -sS -XPOST -H "Content-Type: application/json" \
            -d 'ECRへのPUSHが完了しました' \
            $DISCORD_WEB_HOOK_URL >/dev/null

  ecr_notification:
    steps:
      - slack/status:
          success_message: ':circleci-success: ECRへのPUSHが完了しました'
          failure_message: ':circleci-failed: ECRへのPUSHに失敗しました'
          webhook: '${SLACK_WEBHOOK}'

  deploy_notification:
    steps:
      - slack/status:
          success_message: ':circleci-success: $CIRCLE_BRANCH のデプロイが完了しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-failed: $CIRCLE_BRANCH のデプロイに失敗しました\n\n:github-wh: User：$CIRCLE_USERNAME'
          webhook: '${SLACK_WEBHOOK}'

# ---------------- Jobs ----------------

jobs:
  test:
    machine: true
    steps:
      - checkout
      - env_setup
      - docker_setup
      - laravel_setup
      - test_run
      - fixer_run
      - test_notification_to_discord
      # - test_notification

  ecr_push:
    machine: true
    steps:
      - api_image_push
      - nginx_image_push
      - ecr_notification_to_discord
      # - ecr_notification

  deploy_main:
    machine: true
    steps:
      - ecs_fargate_deploy
      - deploy_notification

# ---------------- Workflows ----------------

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
                ignore: main

  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
                only: main
      # - ecr_push:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #           only: main
      # # - deploy_main:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #           only: main
